apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-migration
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: liquibase
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          workingDir: /liquibase
          command: ["liquibase"]
          args: ["update"]
          env:
            - name: LB_URL
              value: "{{ .Values.liquibase.url }}"
            - name: LB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret.name }}
                  key: username
            - name: LB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret.name }}
                  key: password
            - name: LB_CHANGELOG_FILE
              value: "{{ .Values.liquibase.changeLogFile }}"
          volumeMounts:
            - name: liquibase-changelogs
              mountPath: /liquibase
      volumes:
        - name: liquibase-changelogs
          configMap:
            name: liquibase-changelogs