name: liquibase-ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  liquibase-validate:
    name: Validate Liquibase Changelogs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download Liquibase
        run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v5.0.1/liquibase-5.0.1.zip -o liquibase.zip
          unzip liquibase.zip -d liquibase
          echo "$PWD/liquibase" >> $GITHUB_PATH

      - name: Validate changelog
        env:
          LB_URL: ${{ secrets.LB_CI_URL }}
          LB_USERNAME: ${{ secrets.LB_CI_USERNAME }}
          LB_PASSWORD: ${{ secrets.LB_CI_PASSWORD }}
        run: |
          liquibase \
            --url="$LB_URL" \
            --username="$LB_USERNAME" \
            --password="$LB_PASSWORD" \
            --changeLogFile=changelog-master.xml \
            validate


  build-and-push:
    name: Build & Push Liquibase Image to GHCR
    needs: liquibase-validate
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only after PR merge

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest


  update-gitops:
    name: Update GitOps Repo with New Image Tag
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: krishnakumar-sudala/argocd-gitops-apps
          token: ${{ secrets.GH_PAT }}
          path: gitops

      - name: Update Liquibase image tag in Helm values
        run: |
          sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|" db-platform-liquibase\helm\liquibase-users\values-dev.yaml

      - name: Commit and push changes
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update Liquibase image to ${{ github.sha }}"
          git push