name: liquibase-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  liquibase-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download Liquibase
        run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v5.0.1/liquibase-5.0.1.zip -o liquibase.zip
          unzip liquibase.zip -d liquibase
          echo "$PWD/liquibase" >> $GITHUB_PATH

      - name: Validate changelog
        env:
          LB_URL: ${{ secrets.LB_CI_URL }}
          LB_USERNAME: ${{ secrets.LB_CI_USERNAME }}
          LB_PASSWORD: ${{ secrets.LB_CI_PASSWORD }}
        run: |
          liquibase \
            --url="$LB_URL" \
            --username="$LB_USERNAME" \
            --password="$LB_PASSWORD" \
            --changeLogFile=changelog-master.xml \
            validate